[package]
name = "rucc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
preprocessor = { path = "./preprocessor/" }
compiler = { path = "./compiler/" }

[[bin]]
name = "rucc"
path = "src/main.rs"

[workspace]
members = [
  "preprocessor",
  "compiler"
]

exclude = [
  "fuzzer"
]
