name: Test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        # have to use macos-13 because newer versions are arm-based
        os: [ubuntu-latest, macos-13]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace

      - name: snapshot tests
        run: |
         chmod +x ./tests/snapshot_tests.sh
         ./tests/snapshot_tests.sh
        shell: bash
